server:
  port: 8082
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  data:
    mongodb:
      database: bank
      host: localhost
      port: 27017
